{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
{{ include "generic-app.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
