{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
{{ include "generic-app.labels" . | indent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{-  range $key, $value := .Values.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  selector:
    matchLabels:
{{ include "generic-app.labels" . | indent 6 }}
    {{-  range $key, $value := .Values.serviceLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - path: "{{ .Values.serviceMonitor.path }}"
      port: "{{ .Values.serviceMonitor.port }}"
      interval: "{{ .Values.serviceMonitor.interval }}"
{{- end }}
